name: Publish Blazor Server App

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - run: dotnet --info
    - run: dotnet publish src/BlazorTestApp.csproj --configuration Release -v d
    - uses: actions/upload-artifact@v3
      with:
        name: Build files
        path: |
          src/wwwrot
          src/bin/
          src/obj
